backend:
  name: github
  # change repo to your git repository url
  branch: master
  repo: fahadsaleemfd/blueSky
media_folder: static/assets
public_folder: /assets

collections:
  - name: blueEconomy
    label: BlueEconomy
    label_singular: Slider Image
    folder: src/pages/posts/blueEconomy/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BlueEconomy.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Video '
        name: 'video'
        widget: 'file'
        required: true
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }
  - name: beStartup
    label: BE Startup
    label_singular: Slider Image
    folder: src/pages/posts/beStartups/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE Startups.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }

  - name: beChallenge
    label: BE Challenge 2021
    label_singular: Be Challenge 2021
    folder: src/pages/posts/beChallenge/
    summary: '{{title1}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE  BE Challenge 2021.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Image '
        name: 'image1'
        widget: 'image'
        required: true
      - { label: 'description1', name: 'description', widget: 'string' }
        fields:
          - label: 'Post Settings'
          - name: 'posts'
            widget: 'object'
            fields:
              - {
                  label: 'Prepartaion'
                  name: predesc
                  widget: 'string'
                  tagname: 'h2'
                }
              - { label: 'Round 1', name: round1, widget: string }

  - name: ideathon
    label: Ideathon
    label_singular: Be Challenge 2021
    folder: src/pages/posts/ideaThon/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BE  BE Challenge 2021.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: 'Image '
        name: 'image'
        widget: 'image'
        required: true
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }